Repository getzoop/zoop-sample-taponphone-android, pull requests merged in 2025-04, with the labels that each got.

#15 Delete .github/workflows/dependency-review.yml
  .github/workflows/blockMerge.yml
  .github/workflows/dependency-review.yml
  .github/workflows/sast.yml
Labels: Review effort 1/5, Other

#14 feat: adiciona workflow appsec
  .github/workflows/run_security_check.yml
Labels: BLOCK_PR

#17 Update sdk dependency version
  app/src/main/java/com/zoop/sdk/taponphone/sample/MainActivity.kt
  app/src/main/java/com/zoop/sdk/taponphone/sample/PaymentViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement, Review effort 2/5
